version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: postgresDB
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    volumes:
      - ./back/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432


  pgdamin4:
    image: dpage/pgadmin4:7
    container_name: pgadmin4
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: 12345678
      PGADMIN_DEFAULT_EMAIL: root@root.com
    ports:
      - 8020:80

  php:
    build:
      context: ./back/
      dockerfile:  ./_docker/php/Dockerfile
    depends_on:
      - db
    volumes:
      - ./back/:/var/www
      - /var/www/vendor
    
    container_name: php

  nginx:
    container_name: nginx
    build:
      context: ./back/
      dockerfile:  ./_docker/nginx/Dockerfile
    volumes:
      - ./back/:/var/www
      - /var/www/vendor
      - ./back/_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./back/_docker/nginx/sites/:/etc/nginx/sites-available
      - ./back/_docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"

  node:
    build:
      context: ./front/
      dockerfile:  _docker/node/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front/:/app
      - /app/node_modules
      - ./back/dist/:/app/dist/
    container_name: front_node
    command: npm run build
    

